---
joinmessages:
  - "§c           ✨ DarkRealms Factions ✨"
  - "§d➤    Shop: Shop.DR-PVP.US | /vote for Crate Keys"
  - "§d➤    Forums: dr-pvp.us | Factions War 12/10"
  - "§c           ✨ DarkRealms Factions ✨"
...

