---
joinmessages:
  - "§c           ✨ DarkRealms Factions ✨"
  - "§d➤    Shop: Shop.play-dr.ney | /vote for Vote Keys"
  - "§d➤    Forums: play-dr.net | Factions War 7/5"
  - "§c           ✨ DarkRealms Factions ✨"
...

